name: my_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  # تم تحديث هذا السطر ليستخدم إصدارًا حديثًا من Dart
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  cloud_firestore: ^4.17.4
  url_launcher: ^6.3.1
  country_picker: ^2.0.27
  google_nav_bar: ^5.0.6
  shimmer: ^3.0.0
  intl: ^0.19.0
  http: ^1.2.1
  custom_refresh_indicator: ^3.0.0
  cloud_functions: 4.7.4
  webview_flutter: ^4.13.0
  google_fonts: ^6.3.1
  flutter_animate: ^4.5.2
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  animated_background: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/