// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVH0nqim8zc5k8cMd3hE9UVHUfGUHh2_4',
    appId: '1:647312663571:web:c478189db060556bf74be6',
    messagingSenderId: '647312663571',
    projectId: 'my1app1trade',
    authDomain: 'my1app1trade.firebaseapp.com',
    storageBucket: 'my1app1trade.firebasestorage.app',
    measurementId: 'G-8LKYB7E1TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgjgl6QzLdjkbIZX9gMQB1LAty9qPns4M',
    appId: '1:647312663571:android:76a80b56e683766cf74be6',
    messagingSenderId: '647312663571',
    projectId: 'my1app1trade',
    storageBucket: 'my1app1trade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8vPt-KKHlHfS8T74r4Leh-7Onip9wjDU',
    appId: '1:647312663571:ios:0e25ca216af2a5aaf74be6',
    messagingSenderId: '647312663571',
    projectId: 'my1app1trade',
    storageBucket: 'my1app1trade.firebasestorage.app',
    iosClientId: '647312663571-48r2lvf25lu724u3c0fjkd6hv8ipcnrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

}